### PR TITLE
Fix compilation error introduced in #121

### PR DESCRIPTION
**Pull request by axelson**
It was inadvertently introduced in the merge

### CODE REVIEW

**Comment by cduruk** [comment]
Hi @bryanjos — Thanks for this library. Any chance we could get this merged with a new release? If you want to discuss some other options, feel free to shoot me an email too!

**Comment by bryanjos** [comment]
Sorry, yes I'm on it now. I need to get CI running here again since the travis-ci change, otherwise I would have caught it sooner

**Comment by bryanjos** [comment]
@axelson sorry it took so long, but here is the updated version: https://hexdocs.pm/geo_postgis/3.4.2
